
  name: minisatip
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: SATIP server for linux using local DVB-S2, DVB-C, DVB-T or ATSC cards
  description: |
    Multi-threaded satip server version 1.2 that runs under Linux and it was tested 
    with DVB-S, DVB-S2, DVB-T, DVB-T2, DVB-C, DVB-C2, ATSC and ISDB-T cards.
    The application is designed to stream the requested data to multiple clients (even with one dvb card) 
    in the same time while opening different pids.

  #base: core18

  architectures:
    - build-on: amd64
      run-on: amd64

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  apps:
    minisatip:
      command: usr/bin/minisatip_wrapper
      daemon: forking
      plugs:
        - dvb
        - network
        - network-bind

  parts:
    minisatip:
      plugin: make
      source: https://github.com/catalinii/minisatip.git
      source-type: git
      override-build: | 
        ./configure --prefix=/usr 
        make DDCI=1
        mkdir -p ../install/usr/bin
        cp minisatip ../install/usr/bin/minisatip
        mkdir -p ../install/usr/share/minisatip/html
        cp -R html/* ../install/usr/share/minisatip/html
        ls -lRa ../
      build-packages:
        - libdvbcsa-dev
        - dvb-apps
        - libssl-dev
      stage-packages:
        - libdvbcsa1
        - dvb-apps
      prime:
        - usr/bin/minisatip
        - usr/lib/libdvbapi.so
        - usr/lib/libdvben50221.so
        - usr/lib/libucsi.so
        - usr/lib/*/libdvbcsa.so.1
        - usr/lib/*/libdvbcsa.so.1.0.1
        - usr/share/minisatip/html
        - etc/*

    wrapper:
      plugin: dump
      source: bin
      organize: 
        bin/minisatip_wrapper: usr/bin/minisatip_wrapper
