
  name: minisatip
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
   

  base: core18

  architectures:
    - build-on: amd64
      run-on: amd64

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    minisatip:
      command: usr/bin/minisatip -f -R /usr/share/minisatip/html
      daemon: simple
      plugs:
        - dvb
        - network
        - network-bind

  parts:
    minisatip:
      plugin: make
      source: https://github.com/catalinii/minisatip.git
      source-type: git
      override-build: | 
        ./configure --prefix=/usr 
        make DDCI=1
        mkdir -p ../install/usr/bin
        cp minisatip ../install/usr/bin/minisatip
        mkdir -p ../install/usr/share/minisatip/html
        cp -R html/* ../install/usr/share/minisatip/html
        ls -lRa ../install
      build-packages:
        - libdvbcsa-dev
        - dvb-apps
        - libssl-dev
      stage-packages:
        - libdvbcsa1
        - dvb-apps
      prime:
        - usr/bin/minisatip
        - usr/lib/libdvbapi.so
        - usr/lib/libdvben50221.so
        - usr/lib/*/libdvbcsa.so.1
        - usr/lib/*/libdvbcsa.so.1.0.1
        - usr/share/minisatip/html
        - etc/*

  
